---
title: "Metabolomics_GrowthCurve"
author: "Lillian Dillard"
date: '2023-05-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(reshape)
library(viridisLite)
library(ggrepel)
```

```{r cars}
colors <- c("#36454F", "#dec5da","#b1615c" )
colors2 <- c("#36454F", "#b1615c","#dec5da" )
```

```{r}
iners_vag_pio_fanny_gc <- read.csv("~/Documents/interactions_paper/od_iners-vag-pio-fanny.csv", header = FALSE)

amnii_bucc_christ_hoyle_gc <- read.csv("~/Documents/interactions_paper/od_amnii-bucc-christ-hoyle.csv", header = FALSE)

aero_pio <- read.csv("~/Documents/interactions_paper/gc_figs/ac_gp_gc.csv", header = FALSE)
```


```{r}
aero_pio$V1 <- as.factor(aero_pio$V1)
aero_pio[-1] <- mutate_all(aero_pio[-1], function(x) as.numeric(as.character(x)))
aero_pio [aero_pio <0 ]<- 0
time <- seq(0,((ncol(aero_pio)-2)*3),by=3)
aero_pio[1,2:ncol(aero_pio)] <- time

mean_ap <- aggregate(. ~ V1, aero_pio, mean)
colnames(mean_ap) <- aero_pio[1,]
mean_ap <- mean_ap[!grepl("Time", mean_ap$`7`),]
mean_melt <- melt(mean_ap)
colnames(mean_melt) <- c("sample", "time", "mean")

sd_ap <- aggregate(. ~ V1, aero_pio, sd)
colnames(sd_ap) <- aero_pio[1,]
sd_ap <- sd_ap[!grepl("Time", sd_ap$`7`),]
sd_melt <- melt(sd_ap)
colnames(sd_melt) <- c("sample", "time", "sd")

meltData3 <- merge(mean_melt, sd_melt)

meltData3$time <- as.factor(as.numeric(as.character(meltData3$time))/60)
meltData3$time <- as.numeric(as.character(meltData3$time))
```

```{r}
iners_vag_pio_fanny_gc$V1 <- as.factor(iners_vag_pio_fanny_gc$V1)
iners_vag_pio_fanny_gc[-1] <- mutate_all(iners_vag_pio_fanny_gc[-1], function(x) as.numeric(as.character(x)))
iners_vag_pio_fanny_gc [iners_vag_pio_fanny_gc <0 ]<- 0
time <- seq(0,((ncol(iners_vag_pio_fanny_gc)-2)*3),by=3)
iners_vag_pio_fanny_gc[1,2:ncol(iners_vag_pio_fanny_gc)] <- time

mean_ivpf <- aggregate(. ~ V1, iners_vag_pio_fanny_gc, mean)
colnames(mean_ivpf) <- iners_vag_pio_fanny_gc[1,]
mean_ivpf <- mean_ivpf[!grepl("Time", mean_ivpf$`10`),]
mean_melt <- melt(mean_ivpf)
colnames(mean_melt) <- c("sample", "time", "mean")

sd_ivpf <- aggregate(. ~ V1, iners_vag_pio_fanny_gc, sd)
colnames(sd_ivpf) <- iners_vag_pio_fanny_gc[1,]
sd_ivpf <- sd_ivpf[!grepl("Time", sd_ivpf$`10`),]
sd_melt <- melt(sd_ivpf)
colnames(sd_melt) <- c("sample", "time", "sd")

meltData <- merge(mean_melt, sd_melt)

meltData$time <- as.factor(as.numeric(as.character(meltData$time))/60)
meltData$time <- as.numeric(as.character(meltData$time))
```

```{r}
amnii_bucc_christ_hoyle_gc$V1 <- as.factor(amnii_bucc_christ_hoyle_gc$V1)
amnii_bucc_christ_hoyle_gc[-1] <- mutate_all(amnii_bucc_christ_hoyle_gc[-1], function(x) as.numeric(as.character(x)))
amnii_bucc_christ_hoyle_gc [amnii_bucc_christ_hoyle_gc <0 ]<- 0
time <- seq(0,((ncol(amnii_bucc_christ_hoyle_gc)-2)*3),by=3)
amnii_bucc_christ_hoyle_gc[1,2:ncol(amnii_bucc_christ_hoyle_gc)] <- time

mean_abch <- aggregate(. ~ V1, amnii_bucc_christ_hoyle_gc, mean)
colnames(mean_abch) <- amnii_bucc_christ_hoyle_gc[1,]
mean_abch <- mean_abch[!grepl("Time", mean_abch$`13`),]
mean_melt <- melt(mean_abch)
colnames(mean_melt) <- c("sample", "time", "mean")

sd_abch <- aggregate(. ~ V1, amnii_bucc_christ_hoyle_gc, sd)
colnames(sd_abch) <- amnii_bucc_christ_hoyle_gc[1,]
sd_abch <- sd_abch[!grepl("Time", sd_abch$`13`),]
sd_melt <- melt(sd_abch)
colnames(sd_melt) <- c("sample", "time", "sd")

meltData2 <- merge(mean_melt, sd_melt)

meltData2$time <- as.factor(as.numeric(as.character(meltData2$time))/60)
meltData2$time <- as.numeric(as.character(meltData2$time))
```


### fanny

```{r pressure, echo=FALSE}
fanny <- meltData %>% filter(sample == c("fanny_blank","fanny_piotti","fanny_vaginalis") & time <= 45)

pdf(file='~/Documents/interactions_paper/gc_figs/fanny.pdf', width=5, height=5)

fanny %>%
  ggplot(aes(x = time, y = mean, group = sample, fill = sample)) +
  geom_line(aes(color=sample), size = 1)+
  geom_ribbon(aes(ymin = mean-sd, ymax = mean+sd), alpha = 0.2, show.legend = FALSE)+
  scale_color_manual(values=colors)+
  scale_fill_manual(values = colors) +
  theme_classic()+
  xlab("Time\n(Hours)")+
  ylab(bquote('Mean Growth'~OD[600]))+
  ggtitle("Fannyhessea vaginae") +
  theme(axis.title.x = element_text(size = 17), axis.text = element_text(size = 13),
        axis.title.y = element_text(size = 17),
        plot.title = element_text(size = 20, face = "bold.italic"))+
  theme(legend.position = "none")+
  ylim(0.00,1.00)

dev.off()
```
### piotti

```{r pressure, echo=FALSE}
piotti <- meltData3 %>% filter(sample == c("piotti_blank","piotti_piotti","piotti_vaginalis") & time <= 45)

pdf(file='~/Documents/interactions_paper/gc_figs/piotti.pdf', width=5, height=5)

piotti %>%
  ggplot(aes(x = time, y = mean, group = sample, fill = sample)) +
  geom_line(aes(color=sample), size = 1)+
  geom_ribbon(aes(ymin = 0, ymax = mean+sd), alpha = 0.2)+
  scale_color_manual(values=colors)+
  scale_fill_manual(values = colors) +
  theme_classic()+
  xlab("Time\n (Hours)")+
  ylab(bquote('Mean Growth'~OD[600]))+
  ggtitle("Gardnerella piotti") +
  theme(axis.title.x = element_text(size = 17), axis.text = element_text(size = 13), 
        axis.title.y = element_text(size = 17),
        plot.title = element_text(size = 20, face = "bold.italic"))+
  theme(legend.position = "none")+
  ylim(0.00,1.00)
dev.off()
```

### vaginalis

```{r pressure, echo=FALSE}
vaginalis <- meltData %>% filter(sample == c("vaginalis_blank","vaginalis_vaginalis", "vaginlis_piotti") & time <= 45)

pdf(file='~/Documents/interactions_paper/gc_figs/vaginalis.pdf', width=5, height=5)

vaginalis %>%
  ggplot(aes(x = time, y = mean, group = sample, fill = sample)) +
  geom_line(aes(color=sample), size = 1)+
  geom_ribbon(aes(ymin = mean-sd, ymax = mean+sd), alpha = 0.2, show.legend = FALSE)+
  scale_color_manual(values=colors2)+
  scale_fill_manual(values = colors2) +
  theme_classic()+
  xlab("Time\n (Hours)")+
  ylab(bquote('Mean Growth'~OD[600]))+
  ggtitle("Gardnerella vaginalis") +
  theme(axis.title.x = element_text(size = 17), axis.text = element_text(size = 13), 
        axis.title.y = element_text(size = 17),
        plot.title = element_text(size = 20, face = "bold.italic"))+
  theme(legend.position = "none")+
  ylim(0.00,1.00)
dev.off()
```
### iners

```{r pressure, echo=FALSE}
iners <- meltData %>% filter(sample == c("iners_blank", "iners_piotti", "iners_vaginalis") & time <= 45)

pdf(file='~/Documents/interactions_paper/gc_figs/iners.pdf', width=5, height=5)

iners %>%
  ggplot(aes(x = time, y = mean, group = sample, fill = sample)) +
  geom_line(aes(color=sample), size = 1)+
  geom_ribbon(aes(ymin = mean-sd, ymax = mean+sd), alpha = 0.2, show.legend = FALSE)+
  scale_color_manual(values=colors)+
  scale_fill_manual(values = colors) +
  theme_classic()+
  xlab("Time\n (Hours)")+
  ylab(bquote('Mean Growth'~OD[600]))+
  ggtitle("Lactobacillus iners") +
  theme(axis.title.x = element_text(size = 17), axis.text = element_text(size = 13), 
        axis.title.y = element_text(size = 17),
        plot.title = element_text(size = 20, face = "bold.italic"))+
  theme(legend.position = "none")+
  ylim(0.00,1.00)
dev.off()
```
### amnii

```{r pressure, echo=FALSE}
amnii <- meltData2 %>% filter(sample == c("amnii_blank", "amnii_piotti", "amnii_vaginalis") & time <= 45)

pdf(file='~/Documents/interactions_paper/gc_figs/amnii.pdf', width=5, height=5)

amnii %>%
  ggplot(aes(x = time, y = mean, group = sample, fill = sample)) +
  geom_line(aes(color=sample), size = 1)+
  geom_ribbon(aes(ymin = mean-sd, ymax = mean+sd), alpha = 0.2, show.legend = FALSE)+
  scale_color_manual(values=colors)+
  scale_fill_manual(values = colors) +
  theme_classic()+
  xlab("Time\n (Hours)")+
  ylab(bquote('Mean Growth'~OD[600]))+
  ggtitle("Prevotella amnii") +
  theme(axis.title.x = element_text(size = 17), axis.text = element_text(size = 13), 
        axis.title.y = element_text(size = 17),
        plot.title = element_text(size = 20, face = "bold.italic"))+
  theme(legend.position = "none")+
  ylim(0.00,1.00)
dev.off()
```
### buccalis

```{r pressure, echo=FALSE}
buccalis <- meltData2 %>% filter(sample == c("buccalis_blank", "buccalis_piotti", "buccalis_vaginalis") & time <= 45)

pdf(file='~/Documents/interactions_paper/gc_figs/buccalis.pdf', width=5, height=5)

buccalis %>%
  ggplot(aes(x = time, y = mean, group = sample, fill = sample)) +
  geom_line(aes(color=sample), size = 1)+
  geom_ribbon(aes(ymin = mean-sd, ymax = mean+sd), alpha = 0.2, show.legend = FALSE)+
  scale_color_manual(values=colors)+
  scale_fill_manual(values = colors) +
  theme_classic()+
  xlab("Time\n (Hours)")+
  ylab(bquote('Mean Growth'~OD[600]))+
  ggtitle("Prevotella buccalis") +
  theme(axis.title.x = element_text(size = 17), axis.text = element_text(size = 13), 
        axis.title.y = element_text(size = 17),
        plot.title = element_text(size = 20, face = "bold.italic"))+
  theme(legend.position = "none")+
  ylim(0.00,1.00)
dev.off()
```
### christensii

```{r pressure, echo=FALSE}
christensii <- meltData3 %>% filter(sample == c("aerococcus_blank", "aerococcus_piotti", "aerococcus_vaginalis") & time <= 45)

pdf(file='~/Documents/interactions_paper/gc_figs/christensii.pdf', width=5, height=5)

christensii %>%
  ggplot(aes(x = time, y = mean, group = sample, fill = sample)) +
  geom_line(aes(color=sample), size = 1)+
  geom_ribbon(aes(ymin = 0, ymax = mean+sd), alpha = 0.2, show.legend = FALSE)+
  scale_color_manual(values=colors)+
  scale_fill_manual(values = colors) +
  theme_classic()+
  xlab("Time\n (Hours)")+
  ylab(bquote('Mean Growth'~OD[600]))+
  ggtitle("Aerococcus christensenii") +
  theme(axis.title.x = element_text(size = 17), axis.text = element_text(size = 13), 
        axis.title.y = element_text(size = 17),
        plot.title = element_text(size = 20, face = "bold.italic"))+
  theme(legend.position = "none")+
  ylim(0.00,1.00)
dev.off()
```
## hoyle
```{r pressure, echo=FALSE}
hoyle <- meltData2 %>% filter(sample == c("hoyle_blank", "hoyle_piotti", "hoyle_vaginalis") & time <= 45)

pdf(file='~/Documents/interactions_paper/gc_figs/hoyle.pdf', width=5, height=5)

hoyle %>%
  ggplot(aes(x = time, y = mean, group = sample, fill = sample)) +
  geom_line(aes(color=sample), size = 1)+
  geom_ribbon(aes(ymin = mean-sd, ymax = mean+sd), alpha = 0.2, show.legend = FALSE)+
  scale_color_manual(values=colors)+
  scale_fill_manual(values = colors) +
  theme_classic()+
  xlab("Time\n (Hours)")+
  ylab(bquote('Mean Growth'~OD[600]))+
  ggtitle("Hoylesella timonensis") +
  theme(axis.title.x = element_text(size = 17), axis.text = element_text(size = 13), 
        axis.title.y = element_text(size = 17),
        plot.title = element_text(size = 20, face = "bold.italic"))+
  theme(legend.position = "none")+
  ylim(0.00,1.00)
dev.off()
```

```{r}
# Set the path to the folder containing the files
folder_path <- "~/Documents/interactions_paper/metabolomics"

# Get a list of filenames in the folder
file_names <- list.files(folder_path, pattern = "*.csv")

# Create an empty list to store the data
data_list <- list()

# Loop through each file and read it into a separate object
for (i in seq_along(file_names)) {
  file <- file_names[i]
  # Read the file using an appropriate function, e.g., read.csv, read.table
  data <- read.csv(file.path(folder_path, file))
  
  # Assign the data to an object with a unique name
  object_name <- file_names[i]
  assign(object_name, data)
  
  # Store the object name in the data_list
  data_list[[i]] <- object_name
}

library(mdthemes)
file_names <- file_names[-c(6, 14)];
data_list <- data_list[-c(6, 14)]
```

```{r}
titles <- list("***A. christensii* in *G. piotti* Spent Media**",
               "***P. buccallis* in *G. piotti* Spent Media**",
               "***F. vaginae* in *G. piotti* Spent Media**",
               "***H. timonensis* in *G. piotti* Spent Media**",
               "***L. iners* in *G. piotti* Spent Media**",
               "***P. amnii* in *G. piotti* Spent Media**",
               "***G. vaginalis* in *G. piotti* Spent Media**",
               "***A. christensii* in *G. vaginalis* Spent Media**",
               "***P. buccallis* in *G. vaginalis* Spent Media**",
               "***F. vaginae* in *G. vaginalis* Spent Media**",
               "***H. timonensis* in *G. vaginalis* Spent Media**",
               "***L. iners* in *G. vaginalis* Spent Media**")
```


```{r}
for (i in seq_along(file_names)) {
  file <- eval(parse(text = data_list[i]))
  file$log2.FC. <- log2(1/file$FC)
  file$diffexpressed <- "Not Significant"
  file$diffexpressed[file$log2.FC. >= 2 & file$p.ajusted < 0.01] <- "Produced"
  file$diffexpressed[file$log2.FC. <= -2 & file$p.ajusted < 0.01] <- "Consumed"
  file$X <- tolower(file$X)
  file$delabel <- NA
  file$delabel[file$diffexpressed != "Not Significant"] <- file$X[file$diffexpressed != "Not Significant"]
  file_name <- paste0("~/Documents/interactions_paper/metabolomics/figures/",file_names[i], ".pdf")
  object_name <- paste0("info_",file_names[i])
  pdf(file_name, height = 5.5)
  print(ggplot(data=file, aes(x=log2.FC., y=-log10(p.ajusted), col=diffexpressed, label=delabel)) +
          geom_point() + 
          theme_classic() +
          geom_text_repel(size = 5) +
          scale_color_manual(values=c("#77c3ec", "grey","#597d35")) +
          geom_vline(xintercept=c(-2, 2), col="black") +
          geom_hline(yintercept=-log10(0.01), col="black")+ 
    mdthemes::md_theme_classic() +
    labs(x = "log2 Fold Change", y = "-log10(p-value)",
         color = NULL,
         title = titles[i]) +
      theme(legend.position = "none"))
  dev.off()
  
  file$comparison <- file_names[i]
  assign(object_name, file)
}
```


# Metabolomics Volcano Plots
```{r}
Dysreg_PiottivsMedia.csv$diffexpressed <- "Not Significant"
Dysreg_PiottivsMedia.csv$diffexpressed[Dysreg_PiottivsMedia.csv$log2.FC. >= 2 & Dysreg_PiottivsMedia.csv$p.ajusted < 0.01] <- "Produced"
Dysreg_PiottivsMedia.csv$diffexpressed[Dysreg_PiottivsMedia.csv$log2.FC. <= -2 & Dysreg_PiottivsMedia.csv$p.ajusted < 0.01] <- "Consumed"
Dysreg_PiottivsMedia.csv$X <- tolower(Dysreg_PiottivsMedia.csv$X)
Dysreg_PiottivsMedia.csv$delabel <- NA
Dysreg_PiottivsMedia.csv$delabel[Dysreg_PiottivsMedia.csv$diffexpressed != "Not Significant"] <- Dysreg_PiottivsMedia.csv$X[Dysreg_PiottivsMedia.csv$diffexpressed != "Not Significant"]
Dysreg_PiottivsMedia.csv$comparison <- "Dysreg_PiottivsMedia.csv"

pdf("~/Documents/interactions_paper/metabolomics/figures/Dysreg_PiottivsMedia.csv.pdf",height = 5.5)
print(ggplot(data=Dysreg_PiottivsMedia.csv, aes(x=log2.FC., y=-log10(p.ajusted), col=diffexpressed, label=delabel)) +
        geom_point() + 
        theme_classic() +
        geom_text_repel(size = 4) +
        scale_color_manual(values=c("#77c3ec", "grey","#597d35")) +
        geom_vline(xintercept=c(-2, 2), col="black") +
        geom_hline(yintercept=-log10(0.01), col="black")+ 
  mdthemes::md_theme_classic() +
  labs(x = "log2 Fold Change", y = "-log10(p-value)",
        color = NULL,
        title = "***G. piotti* in Fresh Media**") +
    theme(legend.position = "none"))
dev.off()
```

```{r}
Dysregulated_VagvsMedia.csv$diffexpressed <- "Not Significant"
Dysregulated_VagvsMedia.csv$diffexpressed[Dysregulated_VagvsMedia.csv$log2.FC. >= 2 & Dysregulated_VagvsMedia.csv$p.ajusted < 0.01] <- "Produced"
Dysregulated_VagvsMedia.csv$diffexpressed[Dysregulated_VagvsMedia.csv$log2.FC. <= -2 & Dysregulated_VagvsMedia.csv$p.ajusted < 0.01] <- "Consumed"
Dysregulated_VagvsMedia.csv$X <- tolower(Dysregulated_VagvsMedia.csv$X)
Dysregulated_VagvsMedia.csv$delabel <- NA
Dysregulated_VagvsMedia.csv$delabel[Dysregulated_VagvsMedia.csv$diffexpressed != "Not Significant"] <- Dysregulated_VagvsMedia.csv$X[Dysregulated_VagvsMedia.csv$diffexpressed != "Not Significant"]
Dysregulated_VagvsMedia.csv$comparison <- "Dysregulated_VagvsMedia.csv"

pdf("~/Documents/interactions_paper/metabolomics/figures/Dysregulated_VagvsMedia.csv.pdf", height = 5.5)
print(ggplot(data=Dysregulated_VagvsMedia.csv, aes(x=log2.FC., y=-log10(p.ajusted), col=diffexpressed, label=delabel)) +
        geom_point() + 
        theme_classic() +
        geom_text_repel(size = 4) +
        scale_color_manual(values=c("#77c3ec", "grey","#597d35")) +
        geom_vline(xintercept=c(-2, 2), col="black") +
        geom_hline(yintercept=-log10(0.01), col="black")+ 
  mdthemes::md_theme_classic() +
  labs(x = "log2 Fold Change", y = "-log10(p-value)",
        color = NULL,
        title = "***G. vaginalis* in Fresh Media**")+
    theme(legend.position = "none"))
dev.off()
```

```{r}
list_join <- list(info_Dysreg_PiottivsAero.csv,
                              info_Dysreg_PiottivsBucallis.csv, info_Dysreg_PiottivsFanny.csv,
                              info_Dysreg_PiottivsHoy.csv, info_Dysreg_PiottivsLacto.csv,
                              Dysreg_PiottivsMedia.csv, info_Dysreg_PiottivsPa.csv,
                              info_Dysreg_PiottivsVaginallis.csv, info_Dysreg_VagvsAero.csv,
                              info_Dysreg_VagvsBucallis.csv, info_Dysreg_VagvsFanny.csv, 
                              info_Dysreg_VagvsHoy.csv, info_Dysreg_VagvsLact.csv,
                              Dysregulated_VagvsMedia.csv)
metabo_info_all <- list_join %>% reduce(rbind, by='X')
metabo_info_all$FC <- NULL
metabo_info_all$X.log10.p. <- NULL
metabo_info_all$delabel <- NULL
write.csv(metabo_info_all, "~/Documents/interactions_paper/metaboinfoall.csv")
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
